[package]
name = "omv"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap = { version = "4.6.6", features = ["derive"] }
crossterm = "0.29.0"
omv-config.workspace = true
omv-core.workspace = true
omv-find.workspace = true
omv-lsp.workspace = true
omv-syntax.workspace = true
portable-pty = "0.9"
ratatui = "0.30.2"
tracing.workspace = true
tracing-subscriber = "0.3.23"
unicode-width = "0.2.2"
vt100 = "0.16"

[dev-dependencies]
serde_yaml_ng = "0.10.0"
