[package]
name = "omv-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
dirs = "6.0.0"
omv-core = { version = "0.1.0", path = "../omv-core" }
serde.workspace = true
serde_yaml_ng = "0.10.0"
thiserror.workspace = true
