[package]
name = "omv-syntax"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
omv-core = { version = "0.1.0", path = "../omv-core" }
streaming-iterator = "0.1.9"
tree-sitter = "0.26.13"
tree-sitter-json = "0.24.8"
tree-sitter-rust = "0.24.2"
